package pl.edu.agh.handy.offers.model;

/**
 * Possible combination for searching.
 */
public enum SmartSearch {
    NO_SEARCH,
    KEYWORDS,
    LOCATION,
    RADIUS,
    CATEGORY,
    START_DATE,
    END_DATE,
    KEYWORDS_RADIUS,
    KEYWORDS_LOCATION,
    KEYWORDS_LOCATION_RADIUS,
    KEYWORDS_CATEGORY,
    KEYWORDS_START_DATE,
    KEYWORDS_END_DATE,
    KEYWORDS_START_DATE_END_DATE,
    KEYWORDS_LOCATION_CATEGORY_RADIUS,
    KEYWORDS_LOCATION_START_DATE_RADIUS,
    KEYWORDS_LOCATION_END_DATE_RADIUS,
    KEYWORDS_LOCATION_START_DATE_END_DATE_RADIUS,
    KEYWORDS_LOCATION_START_DATE_CATEGORY_RADIUS,
    KEYWORDS_LOCATION_END_DATE_CATEGORY_RADIUS,
    KEYWORDS_LOCATION_START_DATE_END_DATE_CATEGORY_RADIUS;

    public static String getName(SmartSearch smartSearch) {
        return smartSearch.toString();
    }
}
